=== jmstoolkit/pipeline/dtd/action.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT action (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT destinations (input, output?, replyto?)>
<!ELEMENT replyto (#PCDATA)>
<!ELEMENT input (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT plugin (action, name, version, type, url?, work, destinations)>
<!ATTLIST plugin
  xmlns:xsi CDATA #IMPLIED
  xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>
<!ELEMENT work (#PCDATA)>

=== jmstoolkit/pipeline/example/action-echo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "dtd/action.dtd">
<plugin>
  <action>new</action>
  <name>ECHO2</name>
  <version>1</version>
  <type>com.jmstoolkit.pipeline.plugin.Echo</type>
  <!-- the configuration for the plugin goes in the work tag -->
  <work>
  <![CDATA[ 
  ]]>
  </work>
  <destinations>
    <input>dynamicTopics/PL2.INPUT</input>
    <output>dynamicTopics/PL2.OUTPUT</output>
    <replyto>dynamicTopics/PL.REPLYTO</replyto>
  </destinations>
</plugin>

=== jmstoolkit/pipeline/example/action.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "dtd/action.dtd">
<plugin>
  <action>start</action>
  <name>XSL1</name>
  <version>1</version>
  <type>com.jmstoolkit.pipeline.plugin.XSLTransformer</type>
  <!-- the configuration for the plugin goes in the work tag -->
  <work>
  <![CDATA[ 
  ]]>
  </work>
  <destinations>
    <input>dynamicTopics/PL1.INPUT</input>
    <output>dynamicTopics/PL2.INPUT</output>
    <replyto>dynamicTopics/PL.REPLYTO</replyto>
  </destinations>
</plugin>
