=== jmstoolkit/pipeline/dtd/enrich.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT database (driver, url, username, password)>
<!ELEMENT defaultDatabase (driver, url, username, password)>
<!ELEMENT driver (#PCDATA)>
<!ELEMENT dstPath (#PCDATA)>
<!ELEMENT element (srcPath, sql, dstPath?, database?)>
<!ELEMENT elements (element+)>
<!ELEMENT enrich (defaultDatabase, elements)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT sql (#PCDATA)>
<!ELEMENT srcPath (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT username (#PCDATA)>

=== jmstoolkit/pipeline/example/enrich.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE enrich SYSTEM "dtd/enrich.dtd">
<enrich>
  <defaultDatabase>
    <driver>com.mysql.jdbc.MySQLDriver</driver>
    <url>myql://localhost:3306</url>
    <username>test</username>
    <password>test</password>
  </defaultDatabase>
  <elements>
    <element>
      <srcPath>/some/xpath</srcPath>
      <sql>select name from people where name=?</sql>
      <!--dstPath>/some/other/xpath</dstPath-->
      <!-- optional unique DB -->
      <!--database>
        <driver/>
        <url/>
        <username/>
        <password/>
      </database-->
    </element>
  </elements>
</enrich>
