=== jmstoolkit/pipeline/dtd/file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT correlationid (#PCDATA)>
<!ELEMENT correlationiddir (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT properties (#PCDATA)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT timestampformat (#PCDATA)>
<!ELEMENT file (prefix?, name, suffix?, timestamp?, correlationid?, path, correlationiddir?, properties?, timestamp?, timestampformat?)>
<!ATTLIST file
  xmlns:xsi CDATA #IMPLIED
  xsi:noNamespaceSchemaLocation CDATA #IMPLIED
>

=== jmstoolkit/pipeline/example/file.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "dtd/file.dtd">
<file>
  <prefix>swd-</prefix>
  <name>out1</name>
  <suffix>.txt</suffix>
  <correlationid>1</correlationid>
  <path>/Users/scott/work</path>
  <correlationiddir>0</correlationiddir>
  <properties>1</properties>
  <timestamp>1</timestamp>
  <timestampformat>yyyy-MM-dd'T'HH:mm:ss.SSSZ</timestampformat>
</file>
